host = "127.0.0.1"
port = "8081"
expiration_access_hours = 12
expiration_refresh_hours = 48
hasura_url = "https://extrabot.ru/v1/graphql"
new_user_role = "default"

[hasura_credentials]
x_hasura_default_role = "auth_server"
exp = 24
x_hasura_user_id = "4f5621e7-7638-4298-aa0a-042859ab2bfc"
