### Добавить предзапись
POST http://127.0.0.1:8081/auth/login HTTP/1.1
content-type: application/json

{
    "email": "gorlans@mail.ru",
    "password": "12345678"
}
###

POST http://127.0.0.1:8081/signup HTTP/1.1
content-type: application/json

{
    "username": "Andrei",
    "email": "gorlans2@mail.ru",
    "password": "12345678"
}
###

POST http://127.0.0.1:8081/createapikey HTTP/1.1
content-type: application/json

{
    "email": "gorlans@mail.ru",
    "password": "12345678"
}
###


POST http://127.0.0.1:8081/auth/loginapikey HTTP/1.1
content-type: application/json

{
    "api_key": "Iv+9v38CrV+20qaYeyY+Gz5TBL0lgtNynOO7F9u4mFt8Hmim680Nu/JSiyg-GfrIKDtxQzImkKk6WtqJ51Bu2aQT5Xm6"
}
###

POST http://127.0.0.1:8081/empty HTTP/1.1
content-type: application/json

{
    "email": "user@example.com",
    "password": "securepassword"
}